stages:
    - build
    - deploy
    - release

.only_changes: &changes_def
    changes:
      - Dockerfile.pypi
      - Makefile
      - tests/**/*
      - docker-entrypoint.sh

build:
  stage: build
  script:
    - make build test deliver clean
  environment:
    name: snap
  artifacts:
    paths:
      - factory.manifest
  only:
    <<: *changes_def
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update map upgrade
    - $HOME/bin/lzmservicectl update --wait-timeout=500  qgis-worker upgrade 
  environment:
    name: snap
  only:
    <<: *changes_def
  tags:
    - infrav3

release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-map-server
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh
  environment:
    name: production
  when: manual
  tags:
    - infrav3

