stages:
    - build
    - deploy
    - release

.only_changes: &changes_def
    changes:
      - Dockerfile.pypi
      - Makefile
      - tests/**/*
      - docker-entrypoint.sh

variables:
    QGIS_FLAVOR: ltr

build:
  stage: build
  script:
    - make build test deliver clean FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  artifacts:
    paths:
      - factory.manifest
  only:
    <<: *changes_def
  tags:
    - infrav3

deploy_snap:
  stage: deploy
  script:
    - $HOME/bin/lzmservicectl update -C MUTU map --annotate="Updated image $QGIS_FLAVOR ($CI_COMMIT_SHORT_SHA)"
    - $FACTORY_SCRIPTS/push-to-docker-hub.sh
  environment:
    name: snap
  only:
    <<: *changes_def
  tags:
    - infrav3

# Make release job target visible on gitlab
release:ltr:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-map-server-$QGIS_FLAVOR
  environment:
    name: production
  when: manual
  only:
    variables:
      - $QGIS_FLAVOR == "ltr"
  tags:
    - infrav3

# Make release job target visible on gitlab
release:release:
  stage: release
  script:
    - $FACTORY_SCRIPTS/release-image.sh qgis-map-server-$QGIS_FLAVOR
  environment:
    name: production
  when: manual
  only:
    variables:
      - $QGIS_FLAVOR == "release"
  tags:
    - infrav3

